require_relative '../../../../node_modules/@capacitor/ios/scripts/pods_helpers'

platform :ios, '11.0'
use_frameworks!

# workaround to avoid Xcode 10 caching of Pods that requires
# Product -> Clean Build Folder after new Cordova plugins installed
# Requires CocoaPods 1.6 or newer
install! 'cocoapods', :disable_input_output_paths => true

def capacitor_pods
  pod 'Capacitor', :path => '../../../../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../../../node_modules/@capacitor/ios'
  pod 'ByteowlsCapacitorFilesharer', :path => '../../../../node_modules/@byteowls/capacitor-filesharer'
  pod 'CapacitorDataStorageSqlite', :path => '../../../../node_modules/capacitor-data-storage-sqlite'
  pod 'CapawesomeCapacitorFilePicker', :path => '../../../../node_modules/@capawesome/capacitor-file-picker'
  pod 'CapacitorApp', :path => '../../../../node_modules/@capacitor/app'
  pod 'CapacitorBrowser', :path => '../../../../node_modules/@capacitor/browser'
  pod 'CapacitorClipboard', :path => '../../../../node_modules/@capacitor/clipboard'
  pod 'CapacitorDevice', :path => '../../../../node_modules/@capacitor/device'
  pod 'CapacitorFilesystem', :path => '../../../../node_modules/@capacitor/filesystem'
  pod 'CapacitorHaptics', :path => '../../../../node_modules/@capacitor/haptics'
  pod 'CapacitorLocalNotifications', :path => '../../../../node_modules/@capacitor/local-notifications'
  pod 'CapacitorNetwork', :path => '../../../../node_modules/@capacitor/network'
  pod 'CapacitorShare', :path => '../../../../node_modules/@capacitor/share'
end

target 'App' do
  capacitor_pods
  # Add your Pods here
end

post_install do |installer|
  assertDeploymentTarget(installer)
end
