image:
  node:10.16.3

cache:
  untracked: true
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
    - dist/

stages:
  - setup
  - build
  - test
  - deploy

setup:
  stage: setup
  script:
    - npm install

build:
  stage: build
  script:
    - npm run affected:build -- --prod

test:
  stage: test
  script:
    - npm run affected:e2e -- --headless

deploy:
  stage: deploy
  image: mcr.microsoft.com/azure-cli:2.0.80
  rules:
    - when: manual
  script:
    - az storage blob delete-batch --source "\$web" --connection-string $AZURE_STORAGE_CONNECTION_STRING
    - az storage blob upload-batch --destination "\$web" --source dist/apps/website --connection-string $AZURE_STORAGE_CONNECTION_STRING
