image: node:12.15.0

stages:
  - setup
  - build
  - deploy

deploy-field-companion:
  stage: deploy
  only:
    - release/field-companion
  script:
    - npm ci
    - npm run build:field-companion:prod -- --base-href "/field-companion"
    - az storage blob delete-batch --source "\$web/field-companion" --connection-string "$AZURE_STORAGE_CONNECTION_STRING"
    - az storage blob upload-batch --destination "\$web/field-companion" --source apps/field-companion/dist/field-companion --connection-string "$AZURE_STORAGE_CONNECTION_STRING"
