image: node:12.15.0

stages:
  - build
  - deploy

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - dist
    - apps/field-companion/dist/field-companion

build-field-companion:
  stage: build
#  only:
#    - release/field-companion
  script:
    - npm ci
    - npm run build:field-companion:prod -- --base-href "/field-companion"

deploy-field-companion:
  stage: deploy
  image: mcr.microsoft.com/azure-cli:2.0.80
  rules:
    - when: manual
#    - if: '$CI_COMMIT_BRANCH != "release/field-companion"'
  script:
    - az storage blob delete-batch --source "\$web/field-companion" --connection-string "$AZURE_STORAGE_CONNECTION_STRING"
    - az storage blob upload-batch --destination "\$web/field-companion" --source apps/field-companion/dist/field-companion --connection-string "$AZURE_STORAGE_CONNECTION_STRING"
