image:
  node:10.16.3


deploy-website:
  stage: build
  image: mcr.microsoft.com/azure-cli:2.0.80
  rules:
    - when: manual
  script:
    - npm install
    - npm run build:website:prod
    - npm run e2e:website:prod
    - az storage blob delete-batch --source "\$web" --connection-string $AZURE_STORAGE_CONNECTION_STRING
    - az storage blob upload-batch --destination "\$web" --source dist/apps/website --connection-string $AZURE_STORAGE_CONNECTION_STRING
