name: Build & Test (default)

on:
  push:
    branches:
      - '**'
      - '!develop'
      - '!main'
  pull_request:
    branches: [ develop ]

jobs:
  check-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: '12'

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: npm ci

      - name: Check formatting
        run: npm run format:check

      - name: Lint
        run: npm run eslint:error:affected

      - name: Build
        run: npm run affected:build:prod

      - name: Unit tests
        run: npm run affected:test

      - name: Acceptance tests
        run: npm run e2e -- --headless

  sonarcloud:
    name: sonar-cloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

    #  - name: Install dependencies
    #    run: npm ci

   #   - name: Unit tests
   #     run: npm run test:all

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
