name: CI - Field Companion

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v2
        with:
         node-version: '12'
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Run a multi-line script
        run: |
          npm ci
          npm run build:field-companion:prod -- --base-href "/field-companion"

      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: field-companion-dist
          path: apps/field-companion/dist/field-companion/
          if-no-files-found: error

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download Field Companion artifact
        uses: actions/download-artifact@v2
        with:
          name: field-companion-dist

      - name: Empty Field Companion blob storage
        uses: azure/CLI@v1
        env:
          azureConnectionString: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
        with:
          azcliversion: 2.0.80
          inlineScript: |
            az storage blob delete-batch -s "\$web" --pattern "field-companion/*" --connection-string "$azureConnectionString"

      - name: Upload to Field Companion blob storage
        uses: azure/CLI@v1
        env:
          azureConnectionString: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
        with:
          azcliversion: 2.0.80
          inlineScript: |
            az storage blob upload-batch -d "\$web/field-companion" -s "apps/field-companion/dist/field-companion" --connection-string "$azureConnectionString"
