name: CI - Field Companion

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v2
        with:
         node-version: '12'
      - uses: actions/checkout@v2

      - name: Run a multi-line script
        run: |
          npm ci
          npm run build:field-companion:prod -- --base-href "/field-companion"

      - name: Upload to blob storage
        uses: azure/CLI@v1
        env:
          azureConnectionString: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
        with:
          azcliversion: 2.0.72
          inlineScript: |
            az storage blob delete-batch --source "\$web/field-companion" --connection-string "$azureConnectionString"
            az storage blob upload-batch --destination "\$web/field-companion" --source apps/field-companion/dist/field-companion --connection-string "$azureConnectionString"
